config/routes.rb
Rails.application.routes.draw do

  resources :tasks, only:[:new, :create, :edit, :update, :destroy]
  resources :lists, only:[:new, :create, :edit, :update, :destroy]
  devise_for :users

  root 'home#index'
  resources :mytodos, only:[:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    
    belongs_to :user
    has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user
    belongs_to :list
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery with: :exception

  def index
    if user_signed_in?
      redirect_to mytodos_path
    end
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to mytodos_path }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to mytodos_path }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to mytodos_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title, :user_id)
    end
    
    # Updates the list partial to render updated content.
    def update_list
      render turbo_stream:
        turbo_stream.replace('lists',
          partial: "partials/lists",
          locals: { list: current_user.lists, list: List.new, task: Task.new})
    end
end

app/controllers/mytodos_controller.rb
class MytodosController < ApplicationController

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    @list = List.new
    @task = Task.new
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to mytodos_path }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to mytodos_path }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to mytodos_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :completed, :list_id, :user_id)
    end
    
    # Updates the list partial to render updated content.
    def update_list
      render turbo_stream:
        turbo_stream.replace('lists',
          partial: "partials/lists",
          locals: { lists: current_user.lists, list: List.new, task: Task.new})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/mytodos_helper.rb
module MytodosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<style>
  body{
    background-color: #f2f2f2;
  }
  .forum-content{
    margin: 0% 10% 0% 10%;
  }
  @media(max-width:476px){
    .forum-content{
      margin: 0% 10% 0% 10%;
    }
  }
  .jumbotron{
    margin: 3% 0% 3% 0%;
    min-height: 80vh;
  }
  .jumbotron h1{
    font-size:2.3vw;
    font-weight: bold;
    color: rgba(0, 0, 0, 0.7);
  }
  .jumbotron p{
    font-size:1.3vw;
    padding-right: 35%;
  }
  @media(max-width:1450px){
      .jumbotron h1{
        font-size:3vw;
      }
      .jumbotron p{
        font-size:1.5vw;
      }
  }
  @media(max-width:1199px){
    .card-user{
        margin: 0% 0% 0% 0%;
    }
  }
  @media(max-width:991px){
      .jumbotron{
        margin: 15% 0% 0% 0%;
      }
      .jumbotron h1{
        font-size:7vw;
      }
      .jumbotron p{
        font-size:3.2vw;
      }
  }
  @media(max-width:476px){
      .jumbotron h1{
        font-size:10vw;
      }
      .jumbotron p{
        font-size:5vw;
      }
  }
  @media(max-width:992px){
    .card-holder{
        margin-bottom: 5%;
    }
  }

  .home-link{
    display: inline;
    color: #4064ac !important;
    transition: none;
  }
  .home-link:hover{
    color: rgba(0, 0, 0, 0.7) !important;
    transition: none;
  }
</style>
<div class="container" >
  <div class="forum-content" >
      <div class=" d-flex justify-content-center mt-5">
          <!-- Jumbotron for welcome -->
          <div class="text-left jumbotron">
              <h1>Welcome to toDoOrNotToDo!</h1>
              <br />
              <p>
              <%= link_to new_user_registration_path, class: "nav-link home-link" do %>Create an account<% end %>
               or 
              <%= link_to new_user_session_path, class: "nav-link home-link" do %>log in<% end %>
              to add, edit, and delete your To-dos.
              </p>
          </div>
          <!--End Jumbotron -->
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>toDoOrNotToDo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="Todoornottodo application allows you to create lists with tasks that may be marked as completed or not.">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", "data-turbolinks-eval": "false", defer: true %>
    
    <!-- Stylesheets for icons-->
    <%= stylesheet_link_tag "font-awesome.min" %>

    <!-- Google ownership verification token-->
    <meta name="google-site-verification" content="Lv-mMvsuPsjrMdPZ80lVpl_woCxbSv0cdMrM655qkpg" />

  </head>

  <body>
  
    <!-- Renders navbar from partials-->
    <%= render partial: 'partials/navbar' %>

    <% if notice %>
      <%= render 'partials/notice' %>
    <% end %>

    <% if alert %>
      <%= render 'partials/alert' %>
    <% end %>

    <%= yield %>

    <!-- Renders footer from partials-->
    <%= render 'partials/footer' %>
    
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Title:</strong>
    <%= list.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= list.user_id %>
  </p>

</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<style>
  body{
    background-color: #ede7dc;
  }
  .btn{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: #18654e;
    background-color: #18654e;
    color:#ffff;
  }
  .btn:hover{
    background-color: #ffff;
    color:#18654e;
  }
  a{
    text-decoration: none;
    color: #18654e;
  }
  a:hover{
    color: rgba(0, 0, 0, 0.7);
  }
  .dropdown select{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: #18654e;
    background-color: #18654e;
    color:#ffff;
    margin-top:1%;
  }
  @media(max-width:512px){
    .card{
      margin-left:0 !important;
      margin-right:0!important;
    }
    .ms-5{
    margin-left:1% !important;

    }
  }
</style>

<div class=" my-5 d-flex justify-content-center">
  <div class=" px-5 pb-5 pt-4" style="width: 45rem;">
    <div class="card  mx-5 mt-5 mb-3">
      <div class="card-header">
        <h2>Create a List</h2>
      </div>
      <div class="card-body">
        <%= form_with(model: @list) do |form| %>
                <% if @list.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(@list.errors.count, "error") %> prohibited this @list from being saved:</h2>

                    <ul>
                      <% @list.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group" >
                  <%= form.label :title, style: "display: block" %>
                  <%= form.text_field :title, class: "form-control", :required => true %>
                </div>
                <br/>
                <div class="form-group">
                  <%= form.label :user_id, style: "display: none" %>
                  <%= form.number_field :user_id, id: :tourist_guide_item_user_id, value: current_user.id, type: :hidden %>
                </div>
                <div>
                  <%= form.submit  "Create Post", class: "btn" %>
                </div>
                <br/>
        <% end %>
        <div>
          <%= link_to "Back to My Area", root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<style>
  body{
    background-color: #ede7dc;
  }
  .forum-content{
    margin: 4% 20% 5% 20%;
    padding: 2%;
    background-color: #f2f2f2;
  }
    .col-xl-8 h1{
    color:#18654e;
    margin-bottom: 7%;
    }
    .col-xl-8 p{
    font-size:1vw;
    margin-bottom:4%;
    }
    .col-xl-4{
      justify-content: center;
    }
  @media(max-width:1199px){
    .col-xl-4{
      justify-content: start
    }
  }
  @media(max-width:476px){
    .forum-content{
      margin: 0% 10% 5% 10%;
    }
  }
  .btn{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: #18654e;
    background-color: #18654e;
    color:#ffff;
    transition: none;
  }
  .btn:hover{
    background-color: #ffff;
    color:#18654e;
    transition: none;
  }
  .comments-count{
    margin: 2% 0% 4% 0%;
  }
  .new-comment{
    padding: 4%;
  }
  .card-body h3{
    margin-bottom: 2%;
  }
  .card-body h5{
    margin: 4% 0% 4% 0%;
    color: #18654e;
  }
  @media(max-width:1450px){
      .col-xl-8 p{
        font-size:1.3vw;
      }
  }
  @media(max-width:1022px){
      .col-xl-8 p{
        font-size:1.9vw;
      }
    .forum-content{
        margin: 4% 10% 5% 10%;
    }
  }
  @media(max-width:810px){
      .col-xl-8 p{
        font-size:2.4vw;
      }
  }
  @media(max-width:576px){
      .col-xl-8 p{
        font-size:3vw;
      }
  }
  @media(max-width:448px){
      .col-xl-8 p{
        font-size:4vw;
      }
  }
</style>
<div class="forum-content" >
    <div class="row mx-0 mt-5" >
        <div class="col-xl-8 p-0">
            <h1><%= @list.title %></h1>
        </div>
        <div class="col-xl-4 p-0 d-flex" >
            <div class="d-flex justify-content-center btn-posts">
                <p><%= @list.created_at.mday %>/<%= @list.created_at.month %>/<%= @list.created_at.year %></p>
            </div>
        </div>
    </div>
</div>

app/views/mytodos/index.html.erb
<style>
    body{
    background-color: #f2f2f2;
    }
    .forum-content{
    margin: 0% 10% 0% 10%;
    }
    @media(max-width:476px){
    .forum-content{
        margin: 0% 5% 0% 5%;
    }
    }
    .jumbotron{
    margin: 1% 0% 1% 0%;
    }
    .jumbotron h1{
    font-size:2vw;
    font-weight: bold;
    color: rgba(0, 0, 0, 0.7);
    }
    .jumbotron p{
    font-size:1.3vw;
    padding-right: 15%;
    }
    .list-title{
        font-size:1.1vw;
    }
    @media(max-width:1450px){
        .jumbotron h1{
        font-size:3vw;
        }
        .jumbotron p{
        font-size:1.5vw;
        }
        .list-title{
            font-size:1.3vw;
        }
    }
    @media(max-width:1199px){
    .card-user{
        margin: 0% 0% 0% 0%;
    }
    }
    @media(max-width:991px){
        .jumbotron{
        margin: 15% 0% 0% 0%;
        }
        .jumbotron h1{
        font-size:7vw;
        }
        .jumbotron p{
        font-size:3.2vw;
        }
        .list-title{
            font-size:2.8vw;
        }
    }
    @media(max-width:476px){
        .jumbotron h1{
            font-size:10vw;
        }
        .jumbotron p{
            font-size:5vw;
        }
        .list-title{
            font-size:4vw;
        }
    }
    @media(max-width:992px){
    .card-holder{
        margin-bottom: 5%;
    }
    }
    @media(max-width:799px){
    .lists-flow{
        justify-content: center !important;
        flex-direction: column !important;
    }
    }
    .card-user{
    margin: 7% 0% 5% 5%;
    padding: 2% 1% 3% 1%;
    }
    @media(max-width:1199px){
    .card-user{
        margin: 7% 0% 0% 0%;
        padding: 2% 1% 3% 1%;
    }
    }
    .btn-card{
    margin: 2% 2% 2% 0%;
    }
    .btn-edit{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: rgba(0, 0, 0, 0.7);
    background-color: rgba(0, 0, 0, 0.7);
    color: #ffff;
    transition: none;
    }
    .btn-edit:hover{
    background-color: #ffff;
    color: rgba(0, 0, 0, 1);
    border-color: rgba(0, 0, 0, 0.7);
    transition: none;
    }
    .btn-danger{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: #dc3545;
    transition: none;
    }
    .btn-danger:hover{
    background-color: white;
    color:#dc3545;
    transition: none;
    }
    .card-body-posts p:first-child{
    color: rgba(0, 0, 0, 0.55);
    }
    .card-body-posts{
    text-decoration: none;
    color: #18654e;
    transition: none;
    }
    .card-body-posts:hover{
    color: rgba(0, 0, 0, 0.7) !important;
    transition: none;
    }

    .btn-posts-card-delete{
    color: #dc3545 !important;
    border-style: none;
    background-color: transparent;
    }
    .btn-posts-card-delete:hover{
    color: rgba(0, 0, 0, 0.7) !important;
    transition: none;
    }
    .check-btn{
    background-color: white;
    border-style: none;
    }
    .new-list-btn{
    background-color: #f2f2f2;
    border-style: none;
    }

    .new-list-icon{
    color: #18654e;
    transform: scale(3);
    }

    .new-list-btn:hover > .new-list-icon{
    color: rgba(0, 0, 0, 0.7);
    }
    .card-container{
        padding-left: 0 !important;
        min-height:50vh;
    }
    .modal-buttons{
        border-width: 2px;
        border-color: rgba(0, 0, 0, 0.7);
        background-color: rgba(0, 0, 0, 0.7);
        color: #ffff;
        transition: none;
    }
    .modal-buttons:hover{
        background-color: #f8f9fa;
        border-color: rgba(0, 0, 0, 0.7);
        color: rgba(0, 0, 0, 1);
        transition: none;
    }

    .list-name-container{
        overflow-x: auto;
    }
    .tasks-container{
        max-height: 15rem;
        overflow-y: auto;
    }
    .task-name-container{
        overflow-x: auto;
    }
    .lists-card{
        margin-right: 5%;
    }

</style>


<div class="row forum-content" >

    <!-- Jumbotron weolcome -->
    <div class="col-lg-8 p-0 d-flex align-items-center">
        <div class="text-left jumbotron">
            <h1>Welcome to your to-do's page</h1>
            <br />
            <p>Here you can add, edit, and delete your to-do lists.</p>
        </div>
    </div>
    <!--End Jumbotron -->
    
    <!--Profile card -->
    <div class="col-lg-4 p-0 d-flex justify-content-center card-holder" >
        <div class="card card-user text-start">
            <div class="card-body">
                <h2 class="card-title my-3">Profile:</h2>
                <h3 class="card-title my-3"><%= current_user.email %></h3>
                <br/>
                <%= link_to "Edit password", edit_user_registration_path, class: "nav-link", class: "btn btn-edit btn-card" %>

                <!-- Button trigger modal for account cancellation -->
                <button type="button" class="btn btn-danger btn-card" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete account</button>
                <!-- Modal for account cancellation -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header d-flex justify-content-center">
                                <h3 class="modal-title ms-4 my-2" id="exampleModalLabel">Are you sure to delete your account?</h3>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h5 class="modal-title mx-4 my-2" id="exampleModalLabel">All your personal data will be errased from the system.</h5>
                            </div>
                            <div class="modal-footer d-flex justify-content-center">
                                <%= button_to "Delete my account", registration_path(current_user), method: :delete, class: "btn btn-danger my-2" %>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End Modal -->

            </div>
        </div>
    </div>
    <!-- End profile card -->

    <hr />

    <%= render "partials/lists", lists: current_user.lists, list: @list, task: @task %>

</div>

app/views/partials/_alert.html.erb
<style>
  .alert{
    margin: 0 !important;
  }
</style>
<div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong><%= alert %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/partials/_footer.html.erb
<style>
  .links{
    text-decoration: none;
    color: rgba(0, 0, 0, 0.55) !important;
  }
  .links:hover{
    color: rgba(0,0,0,0.7) !important;
    transition: none !important;
  }
</style>

<!-- Footer -->
<footer class="text-center text-lg-start text-muted">

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: #f8f9fa;">
    © 2023 Copyright:
    <a class="text-reset fw-bold links" href="https://www.linkedin.com/in/laszloscheers/" target="_blank">Laszlo Scheers</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/partials/_navbar.html.erb
<style>
  .button_to{
    padding: 0 !important;
  }
  .brand{
    padding-right: 1%;
    color: rgba(0, 0, 0, 0.7) !important;
  }
  .nav-link{
    color: rgba(0, 0, 0, 0.7) !important;
  }
  @media(max-width:1168px){
    .nav-visible{
      font-size: 0.95rem !important;
    }
    .btn-out{
      font-size: 0.95rem !important;
    }
  }
  @media(max-width:1074px){
    .nav-visible{
      font-size: 0.85rem !important;
    }
    .btn-out{
      font-size: 0.85rem !important;
    }
  }
  @media(max-width:1018px){
    .nav-visible{
      font-size: 0.8rem !important;
    }
    .btn-out{
      font-size: 0.8rem !important;
    }
  }
  @media(max-width:992px){
    .nav-visible{
      font-size: 1.1rem !important;
      border: none !important;

    }
    .btn-out{
      font-size: 1.1rem !important;
    }
  }
  .nav-visible{
    border: 2px solid rgba(0, 0, 0, 0.7);
    border-radius: 6px;
    padding-bottom: 0.5rem !important;
    padding-top: 0.3rem !important;
    padding-left: 0.6rem !important;
    padding-right: 0.6rem !important;
    margin-right: 0.5rem !important;
    margin-left: 0.5rem !important;
    transition: none;
    font-size: 1.1rem;
  }
  .nav-visible:hover{
    border: 2px solid rgba(0, 0, 0, 0.7);
    background-color: rgba(0, 0, 0, 0.7);
    color: #ffff !important;
    border-radius: 6px;
    transition: none;
  }
  .fa-user{
    color: rgba(0, 0, 0, 0.7) !important;
  }
  .nav-visible:hover > .fa-user{
    color: #ffff !important;
  }
  .my_links-right{
    padding-bottom: 0.3rem !important;
    padding-top: 0.3rem !important;
    padding-right: 0.3rem !important;
    padding-left: 0 !important;
  }
  .my_links-left{
    padding-bottom: 0.3rem !important;
    padding-top: 0.3rem !important;
    padding-right: 0 !important;
    padding-left: 0.3rem !important;
  }
  .container-fluid{
    margin: 0% 2% 0% 2%;
  }

  @media(max-width:815px){
    .container-fluid{
      margin: 0% 2.5% 0% 2.5%;
    }
  }
  .btn-out{
    border-style: solid;
    border-radius: 5px;
    border-width:2px;
    border-color: rgba(0, 0, 0, 0.7) !important;
    background-color: #f8f9fa !important;
    color:rgba(0,0,0,1) !important;
    transition: none;
    padding: 0.2rem 0.6rem 0.4rem 0.6rem !important;
    font-size: 1.1rem;
  }
  .btn-out:hover{
    border-color: rgba(0, 0, 0, 0.7) !important;
    background-color: rgba(0, 0, 0, 0.7) !important;
    color: #ffff !important;
    transition: none;
  }

  @media(max-width:991px){
    .btn-out{
      margin-top: 0.5rem;
    }
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand ms-3" do %><%= image_tag "/logo.png", alt: "Web Page Logo", width: 40 , height: 40, class: "img-fluid me-2" %><% end %><%= link_to "toDoOrNotToDo", root_path, class: "navbar-brand brand m-0" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".collapse" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse w-100 ">
        <ul class="navbar-nav ms-auto">
            <% if !user_signed_in? %>
                <li class="nav-item active my-1 d-flex justify-content-end align-items-center">
                    <%= link_to new_user_session_path, class: "nav-link nav-visible" do %><i class="me-1 fa fa-user me-2" aria-hidden="true"></i>Log In<% end %>
                </li>
                <li class="nav-item active my-1 d-flex justify-content-end align-items-center">
                    <%= link_to new_user_registration_path, class: "nav-link nav-visible" do %><i class="me-1 fa fa-user me-2" aria-hidden="true"></i>Sign Up<% end %>
                </li>
            <% end %>
            <% if user_signed_in? %>
                <li class="nav-item my-1 ms-3 d-flex justify-content-end align-items-center">
                    <%= button_to "Sign Out", destroy_user_session_path, class: "nav-link bg-light btn-out me-5", method: :delete %>
                </li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>